// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cashier.proto

package com.example.grpc.server.grpcserver.cashier;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.cashier.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
   */
  java.util.List<com.example.grpc.server.grpcserver.cashier.ProtoCashier> 
      getCashiersList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
   */
  com.example.grpc.server.grpcserver.cashier.ProtoCashier getCashiers(int index);
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
   */
  int getCashiersCount();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
   */
  java.util.List<? extends com.example.grpc.server.grpcserver.cashier.ProtoCashierOrBuilder> 
      getCashiersOrBuilderList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
   */
  com.example.grpc.server.grpcserver.cashier.ProtoCashierOrBuilder getCashiersOrBuilder(
      int index);
}
