// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cashier.proto

package com.example.grpc.server.grpcserver.cashier;

/**
 * Protobuf type {@code com.example.grpc.server.grpcserver.cashier.GetResponse}
 */
public  final class GetResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.server.grpcserver.cashier.GetResponse)
    GetResponseOrBuilder {
  // Use GetResponse.newBuilder() to construct.
  private GetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetResponse() {
    cashiers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GetResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              cashiers_ = new java.util.ArrayList<com.example.grpc.server.grpcserver.cashier.ProtoCashier>();
              mutable_bitField0_ |= 0x00000001;
            }
            cashiers_.add(
                input.readMessage(com.example.grpc.server.grpcserver.cashier.ProtoCashier.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        cashiers_ = java.util.Collections.unmodifiableList(cashiers_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.server.grpcserver.cashier.Cashier.internal_static_com_example_grpc_server_grpcserver_cashier_GetResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.server.grpcserver.cashier.Cashier.internal_static_com_example_grpc_server_grpcserver_cashier_GetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.server.grpcserver.cashier.GetResponse.class, com.example.grpc.server.grpcserver.cashier.GetResponse.Builder.class);
  }

  public static final int CASHIERS_FIELD_NUMBER = 1;
  private java.util.List<com.example.grpc.server.grpcserver.cashier.ProtoCashier> cashiers_;
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
   */
  public java.util.List<com.example.grpc.server.grpcserver.cashier.ProtoCashier> getCashiersList() {
    return cashiers_;
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
   */
  public java.util.List<? extends com.example.grpc.server.grpcserver.cashier.ProtoCashierOrBuilder> 
      getCashiersOrBuilderList() {
    return cashiers_;
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
   */
  public int getCashiersCount() {
    return cashiers_.size();
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
   */
  public com.example.grpc.server.grpcserver.cashier.ProtoCashier getCashiers(int index) {
    return cashiers_.get(index);
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
   */
  public com.example.grpc.server.grpcserver.cashier.ProtoCashierOrBuilder getCashiersOrBuilder(
      int index) {
    return cashiers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < cashiers_.size(); i++) {
      output.writeMessage(1, cashiers_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < cashiers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, cashiers_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.server.grpcserver.cashier.GetResponse)) {
      return super.equals(obj);
    }
    com.example.grpc.server.grpcserver.cashier.GetResponse other = (com.example.grpc.server.grpcserver.cashier.GetResponse) obj;

    boolean result = true;
    result = result && getCashiersList()
        .equals(other.getCashiersList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCashiersCount() > 0) {
      hash = (37 * hash) + CASHIERS_FIELD_NUMBER;
      hash = (53 * hash) + getCashiersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.server.grpcserver.cashier.GetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.cashier.GetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.cashier.GetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.cashier.GetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.cashier.GetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.cashier.GetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.cashier.GetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.cashier.GetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.cashier.GetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.cashier.GetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.cashier.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.cashier.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.server.grpcserver.cashier.GetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.server.grpcserver.cashier.GetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.server.grpcserver.cashier.GetResponse)
      com.example.grpc.server.grpcserver.cashier.GetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.server.grpcserver.cashier.Cashier.internal_static_com_example_grpc_server_grpcserver_cashier_GetResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.server.grpcserver.cashier.Cashier.internal_static_com_example_grpc_server_grpcserver_cashier_GetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.server.grpcserver.cashier.GetResponse.class, com.example.grpc.server.grpcserver.cashier.GetResponse.Builder.class);
    }

    // Construct using com.example.grpc.server.grpcserver.cashier.GetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCashiersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (cashiersBuilder_ == null) {
        cashiers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        cashiersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.server.grpcserver.cashier.Cashier.internal_static_com_example_grpc_server_grpcserver_cashier_GetResponse_descriptor;
    }

    public com.example.grpc.server.grpcserver.cashier.GetResponse getDefaultInstanceForType() {
      return com.example.grpc.server.grpcserver.cashier.GetResponse.getDefaultInstance();
    }

    public com.example.grpc.server.grpcserver.cashier.GetResponse build() {
      com.example.grpc.server.grpcserver.cashier.GetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.example.grpc.server.grpcserver.cashier.GetResponse buildPartial() {
      com.example.grpc.server.grpcserver.cashier.GetResponse result = new com.example.grpc.server.grpcserver.cashier.GetResponse(this);
      int from_bitField0_ = bitField0_;
      if (cashiersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          cashiers_ = java.util.Collections.unmodifiableList(cashiers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cashiers_ = cashiers_;
      } else {
        result.cashiers_ = cashiersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.server.grpcserver.cashier.GetResponse) {
        return mergeFrom((com.example.grpc.server.grpcserver.cashier.GetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.server.grpcserver.cashier.GetResponse other) {
      if (other == com.example.grpc.server.grpcserver.cashier.GetResponse.getDefaultInstance()) return this;
      if (cashiersBuilder_ == null) {
        if (!other.cashiers_.isEmpty()) {
          if (cashiers_.isEmpty()) {
            cashiers_ = other.cashiers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCashiersIsMutable();
            cashiers_.addAll(other.cashiers_);
          }
          onChanged();
        }
      } else {
        if (!other.cashiers_.isEmpty()) {
          if (cashiersBuilder_.isEmpty()) {
            cashiersBuilder_.dispose();
            cashiersBuilder_ = null;
            cashiers_ = other.cashiers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cashiersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCashiersFieldBuilder() : null;
          } else {
            cashiersBuilder_.addAllMessages(other.cashiers_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.server.grpcserver.cashier.GetResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.server.grpcserver.cashier.GetResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.grpc.server.grpcserver.cashier.ProtoCashier> cashiers_ =
      java.util.Collections.emptyList();
    private void ensureCashiersIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        cashiers_ = new java.util.ArrayList<com.example.grpc.server.grpcserver.cashier.ProtoCashier>(cashiers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.server.grpcserver.cashier.ProtoCashier, com.example.grpc.server.grpcserver.cashier.ProtoCashier.Builder, com.example.grpc.server.grpcserver.cashier.ProtoCashierOrBuilder> cashiersBuilder_;

    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public java.util.List<com.example.grpc.server.grpcserver.cashier.ProtoCashier> getCashiersList() {
      if (cashiersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cashiers_);
      } else {
        return cashiersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public int getCashiersCount() {
      if (cashiersBuilder_ == null) {
        return cashiers_.size();
      } else {
        return cashiersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public com.example.grpc.server.grpcserver.cashier.ProtoCashier getCashiers(int index) {
      if (cashiersBuilder_ == null) {
        return cashiers_.get(index);
      } else {
        return cashiersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public Builder setCashiers(
        int index, com.example.grpc.server.grpcserver.cashier.ProtoCashier value) {
      if (cashiersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCashiersIsMutable();
        cashiers_.set(index, value);
        onChanged();
      } else {
        cashiersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public Builder setCashiers(
        int index, com.example.grpc.server.grpcserver.cashier.ProtoCashier.Builder builderForValue) {
      if (cashiersBuilder_ == null) {
        ensureCashiersIsMutable();
        cashiers_.set(index, builderForValue.build());
        onChanged();
      } else {
        cashiersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public Builder addCashiers(com.example.grpc.server.grpcserver.cashier.ProtoCashier value) {
      if (cashiersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCashiersIsMutable();
        cashiers_.add(value);
        onChanged();
      } else {
        cashiersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public Builder addCashiers(
        int index, com.example.grpc.server.grpcserver.cashier.ProtoCashier value) {
      if (cashiersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCashiersIsMutable();
        cashiers_.add(index, value);
        onChanged();
      } else {
        cashiersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public Builder addCashiers(
        com.example.grpc.server.grpcserver.cashier.ProtoCashier.Builder builderForValue) {
      if (cashiersBuilder_ == null) {
        ensureCashiersIsMutable();
        cashiers_.add(builderForValue.build());
        onChanged();
      } else {
        cashiersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public Builder addCashiers(
        int index, com.example.grpc.server.grpcserver.cashier.ProtoCashier.Builder builderForValue) {
      if (cashiersBuilder_ == null) {
        ensureCashiersIsMutable();
        cashiers_.add(index, builderForValue.build());
        onChanged();
      } else {
        cashiersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public Builder addAllCashiers(
        java.lang.Iterable<? extends com.example.grpc.server.grpcserver.cashier.ProtoCashier> values) {
      if (cashiersBuilder_ == null) {
        ensureCashiersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cashiers_);
        onChanged();
      } else {
        cashiersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public Builder clearCashiers() {
      if (cashiersBuilder_ == null) {
        cashiers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cashiersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public Builder removeCashiers(int index) {
      if (cashiersBuilder_ == null) {
        ensureCashiersIsMutable();
        cashiers_.remove(index);
        onChanged();
      } else {
        cashiersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public com.example.grpc.server.grpcserver.cashier.ProtoCashier.Builder getCashiersBuilder(
        int index) {
      return getCashiersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public com.example.grpc.server.grpcserver.cashier.ProtoCashierOrBuilder getCashiersOrBuilder(
        int index) {
      if (cashiersBuilder_ == null) {
        return cashiers_.get(index);  } else {
        return cashiersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public java.util.List<? extends com.example.grpc.server.grpcserver.cashier.ProtoCashierOrBuilder> 
         getCashiersOrBuilderList() {
      if (cashiersBuilder_ != null) {
        return cashiersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cashiers_);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public com.example.grpc.server.grpcserver.cashier.ProtoCashier.Builder addCashiersBuilder() {
      return getCashiersFieldBuilder().addBuilder(
          com.example.grpc.server.grpcserver.cashier.ProtoCashier.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public com.example.grpc.server.grpcserver.cashier.ProtoCashier.Builder addCashiersBuilder(
        int index) {
      return getCashiersFieldBuilder().addBuilder(
          index, com.example.grpc.server.grpcserver.cashier.ProtoCashier.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashier.ProtoCashier cashiers = 1;</code>
     */
    public java.util.List<com.example.grpc.server.grpcserver.cashier.ProtoCashier.Builder> 
         getCashiersBuilderList() {
      return getCashiersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.server.grpcserver.cashier.ProtoCashier, com.example.grpc.server.grpcserver.cashier.ProtoCashier.Builder, com.example.grpc.server.grpcserver.cashier.ProtoCashierOrBuilder> 
        getCashiersFieldBuilder() {
      if (cashiersBuilder_ == null) {
        cashiersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.grpc.server.grpcserver.cashier.ProtoCashier, com.example.grpc.server.grpcserver.cashier.ProtoCashier.Builder, com.example.grpc.server.grpcserver.cashier.ProtoCashierOrBuilder>(
                cashiers_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        cashiers_ = null;
      }
      return cashiersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.server.grpcserver.cashier.GetResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.server.grpcserver.cashier.GetResponse)
  private static final com.example.grpc.server.grpcserver.cashier.GetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.server.grpcserver.cashier.GetResponse();
  }

  public static com.example.grpc.server.grpcserver.cashier.GetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetResponse>() {
    public GetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetResponse> getParserForType() {
    return PARSER;
  }

  public com.example.grpc.server.grpcserver.cashier.GetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

