// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Accessory.proto

package com.example.grpc.server.grpcserver.accessory;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.accessory.DeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accessory_id = 1;</code>
   */
  java.lang.String getAccessoryId();
  /**
   * <code>string accessory_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccessoryIdBytes();

  /**
   * <code>string cash_register_id = 2;</code>
   */
  java.lang.String getCashRegisterId();
  /**
   * <code>string cash_register_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getCashRegisterIdBytes();
}
