// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CashRegister.proto

package com.example.grpc.server.grpcserver.cashregister;

public final class CashRegister {
  private CashRegister() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_cashregister_ProtoCashRegister_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_cashregister_ProtoCashRegister_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_cashregister_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_cashregister_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_cashregister_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_cashregister_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_cashregister_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_cashregister_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_cashregister_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_cashregister_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_cashregister_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_cashregister_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_cashregister_CreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_cashregister_CreateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022CashRegister.proto\022/com.example.grpc.s" +
      "erver.grpcserver.cashregister\"7\n\021ProtoCa" +
      "shRegister\022\014\n\004name\030\001 \001(\t\022\024\n\014added_amount" +
      "\030\002 \001(\005\")\n\rDeleteRequest\022\030\n\020cash_register" +
      "_id\030\001 \001(\t\" \n\016DeleteResponse\022\016\n\006report\030\001 " +
      "\001(\t\"\014\n\nGetRequest\"h\n\013GetResponse\022Y\n\rcash" +
      "registers\030\001 \003(\0132B.com.example.grpc.serve" +
      "r.grpcserver.cashregister.ProtoCashRegis" +
      "ter\"i\n\rCreateRequest\022X\n\014cashRegister\030\001 \001" +
      "(\0132B.com.example.grpc.server.grpcserver.",
      "cashregister.ProtoCashRegister\"\034\n\016Create" +
      "Response\022\n\n\002id\030\001 \001(\t2\260\003\n\023CashRegisterSer" +
      "vice\022\200\001\n\003get\022;.com.example.grpc.server.g" +
      "rpcserver.cashregister.GetRequest\032<.com." +
      "example.grpc.server.grpcserver.cashregis" +
      "ter.GetResponse\022\211\001\n\006delete\022>.com.example" +
      ".grpc.server.grpcserver.cashregister.Del" +
      "eteRequest\032?.com.example.grpc.server.grp" +
      "cserver.cashregister.DeleteResponse\022\211\001\n\006" +
      "create\022>.com.example.grpc.server.grpcser",
      "ver.cashregister.CreateRequest\032?.com.exa" +
      "mple.grpc.server.grpcserver.cashregister" +
      ".CreateResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_grpc_server_grpcserver_cashregister_ProtoCashRegister_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_server_grpcserver_cashregister_ProtoCashRegister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_cashregister_ProtoCashRegister_descriptor,
        new java.lang.String[] { "Name", "AddedAmount", });
    internal_static_com_example_grpc_server_grpcserver_cashregister_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_server_grpcserver_cashregister_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_cashregister_DeleteRequest_descriptor,
        new java.lang.String[] { "CashRegisterId", });
    internal_static_com_example_grpc_server_grpcserver_cashregister_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_grpc_server_grpcserver_cashregister_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_cashregister_DeleteResponse_descriptor,
        new java.lang.String[] { "Report", });
    internal_static_com_example_grpc_server_grpcserver_cashregister_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_grpc_server_grpcserver_cashregister_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_cashregister_GetRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_example_grpc_server_grpcserver_cashregister_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_grpc_server_grpcserver_cashregister_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_cashregister_GetResponse_descriptor,
        new java.lang.String[] { "Cashregisters", });
    internal_static_com_example_grpc_server_grpcserver_cashregister_CreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_example_grpc_server_grpcserver_cashregister_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_cashregister_CreateRequest_descriptor,
        new java.lang.String[] { "CashRegister", });
    internal_static_com_example_grpc_server_grpcserver_cashregister_CreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_example_grpc_server_grpcserver_cashregister_CreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_cashregister_CreateResponse_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
