// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CashRegister.proto

package com.example.grpc.server.grpcserver.cashregister;

/**
 * Protobuf type {@code com.example.grpc.server.grpcserver.cashregister.GetResponse}
 */
public  final class GetResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.server.grpcserver.cashregister.GetResponse)
    GetResponseOrBuilder {
  // Use GetResponse.newBuilder() to construct.
  private GetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetResponse() {
    cashregisters_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GetResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              cashregisters_ = new java.util.ArrayList<com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister>();
              mutable_bitField0_ |= 0x00000001;
            }
            cashregisters_.add(
                input.readMessage(com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        cashregisters_ = java.util.Collections.unmodifiableList(cashregisters_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.server.grpcserver.cashregister.CashRegister.internal_static_com_example_grpc_server_grpcserver_cashregister_GetResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.server.grpcserver.cashregister.CashRegister.internal_static_com_example_grpc_server_grpcserver_cashregister_GetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.server.grpcserver.cashregister.GetResponse.class, com.example.grpc.server.grpcserver.cashregister.GetResponse.Builder.class);
  }

  public static final int CASHREGISTERS_FIELD_NUMBER = 1;
  private java.util.List<com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister> cashregisters_;
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
   */
  public java.util.List<com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister> getCashregistersList() {
    return cashregisters_;
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
   */
  public java.util.List<? extends com.example.grpc.server.grpcserver.cashregister.ProtoCashRegisterOrBuilder> 
      getCashregistersOrBuilderList() {
    return cashregisters_;
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
   */
  public int getCashregistersCount() {
    return cashregisters_.size();
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
   */
  public com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister getCashregisters(int index) {
    return cashregisters_.get(index);
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
   */
  public com.example.grpc.server.grpcserver.cashregister.ProtoCashRegisterOrBuilder getCashregistersOrBuilder(
      int index) {
    return cashregisters_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < cashregisters_.size(); i++) {
      output.writeMessage(1, cashregisters_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < cashregisters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, cashregisters_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.server.grpcserver.cashregister.GetResponse)) {
      return super.equals(obj);
    }
    com.example.grpc.server.grpcserver.cashregister.GetResponse other = (com.example.grpc.server.grpcserver.cashregister.GetResponse) obj;

    boolean result = true;
    result = result && getCashregistersList()
        .equals(other.getCashregistersList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCashregistersCount() > 0) {
      hash = (37 * hash) + CASHREGISTERS_FIELD_NUMBER;
      hash = (53 * hash) + getCashregistersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.server.grpcserver.cashregister.GetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.cashregister.GetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.cashregister.GetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.cashregister.GetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.cashregister.GetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.cashregister.GetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.cashregister.GetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.cashregister.GetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.cashregister.GetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.cashregister.GetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.cashregister.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.cashregister.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.server.grpcserver.cashregister.GetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.server.grpcserver.cashregister.GetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.server.grpcserver.cashregister.GetResponse)
      com.example.grpc.server.grpcserver.cashregister.GetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.server.grpcserver.cashregister.CashRegister.internal_static_com_example_grpc_server_grpcserver_cashregister_GetResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.server.grpcserver.cashregister.CashRegister.internal_static_com_example_grpc_server_grpcserver_cashregister_GetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.server.grpcserver.cashregister.GetResponse.class, com.example.grpc.server.grpcserver.cashregister.GetResponse.Builder.class);
    }

    // Construct using com.example.grpc.server.grpcserver.cashregister.GetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCashregistersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (cashregistersBuilder_ == null) {
        cashregisters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        cashregistersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.server.grpcserver.cashregister.CashRegister.internal_static_com_example_grpc_server_grpcserver_cashregister_GetResponse_descriptor;
    }

    public com.example.grpc.server.grpcserver.cashregister.GetResponse getDefaultInstanceForType() {
      return com.example.grpc.server.grpcserver.cashregister.GetResponse.getDefaultInstance();
    }

    public com.example.grpc.server.grpcserver.cashregister.GetResponse build() {
      com.example.grpc.server.grpcserver.cashregister.GetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.example.grpc.server.grpcserver.cashregister.GetResponse buildPartial() {
      com.example.grpc.server.grpcserver.cashregister.GetResponse result = new com.example.grpc.server.grpcserver.cashregister.GetResponse(this);
      int from_bitField0_ = bitField0_;
      if (cashregistersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          cashregisters_ = java.util.Collections.unmodifiableList(cashregisters_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cashregisters_ = cashregisters_;
      } else {
        result.cashregisters_ = cashregistersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.server.grpcserver.cashregister.GetResponse) {
        return mergeFrom((com.example.grpc.server.grpcserver.cashregister.GetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.server.grpcserver.cashregister.GetResponse other) {
      if (other == com.example.grpc.server.grpcserver.cashregister.GetResponse.getDefaultInstance()) return this;
      if (cashregistersBuilder_ == null) {
        if (!other.cashregisters_.isEmpty()) {
          if (cashregisters_.isEmpty()) {
            cashregisters_ = other.cashregisters_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCashregistersIsMutable();
            cashregisters_.addAll(other.cashregisters_);
          }
          onChanged();
        }
      } else {
        if (!other.cashregisters_.isEmpty()) {
          if (cashregistersBuilder_.isEmpty()) {
            cashregistersBuilder_.dispose();
            cashregistersBuilder_ = null;
            cashregisters_ = other.cashregisters_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cashregistersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCashregistersFieldBuilder() : null;
          } else {
            cashregistersBuilder_.addAllMessages(other.cashregisters_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.server.grpcserver.cashregister.GetResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.server.grpcserver.cashregister.GetResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister> cashregisters_ =
      java.util.Collections.emptyList();
    private void ensureCashregistersIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        cashregisters_ = new java.util.ArrayList<com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister>(cashregisters_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister, com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.Builder, com.example.grpc.server.grpcserver.cashregister.ProtoCashRegisterOrBuilder> cashregistersBuilder_;

    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public java.util.List<com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister> getCashregistersList() {
      if (cashregistersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cashregisters_);
      } else {
        return cashregistersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public int getCashregistersCount() {
      if (cashregistersBuilder_ == null) {
        return cashregisters_.size();
      } else {
        return cashregistersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister getCashregisters(int index) {
      if (cashregistersBuilder_ == null) {
        return cashregisters_.get(index);
      } else {
        return cashregistersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public Builder setCashregisters(
        int index, com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister value) {
      if (cashregistersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCashregistersIsMutable();
        cashregisters_.set(index, value);
        onChanged();
      } else {
        cashregistersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public Builder setCashregisters(
        int index, com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.Builder builderForValue) {
      if (cashregistersBuilder_ == null) {
        ensureCashregistersIsMutable();
        cashregisters_.set(index, builderForValue.build());
        onChanged();
      } else {
        cashregistersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public Builder addCashregisters(com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister value) {
      if (cashregistersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCashregistersIsMutable();
        cashregisters_.add(value);
        onChanged();
      } else {
        cashregistersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public Builder addCashregisters(
        int index, com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister value) {
      if (cashregistersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCashregistersIsMutable();
        cashregisters_.add(index, value);
        onChanged();
      } else {
        cashregistersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public Builder addCashregisters(
        com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.Builder builderForValue) {
      if (cashregistersBuilder_ == null) {
        ensureCashregistersIsMutable();
        cashregisters_.add(builderForValue.build());
        onChanged();
      } else {
        cashregistersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public Builder addCashregisters(
        int index, com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.Builder builderForValue) {
      if (cashregistersBuilder_ == null) {
        ensureCashregistersIsMutable();
        cashregisters_.add(index, builderForValue.build());
        onChanged();
      } else {
        cashregistersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public Builder addAllCashregisters(
        java.lang.Iterable<? extends com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister> values) {
      if (cashregistersBuilder_ == null) {
        ensureCashregistersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cashregisters_);
        onChanged();
      } else {
        cashregistersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public Builder clearCashregisters() {
      if (cashregistersBuilder_ == null) {
        cashregisters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cashregistersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public Builder removeCashregisters(int index) {
      if (cashregistersBuilder_ == null) {
        ensureCashregistersIsMutable();
        cashregisters_.remove(index);
        onChanged();
      } else {
        cashregistersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.Builder getCashregistersBuilder(
        int index) {
      return getCashregistersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public com.example.grpc.server.grpcserver.cashregister.ProtoCashRegisterOrBuilder getCashregistersOrBuilder(
        int index) {
      if (cashregistersBuilder_ == null) {
        return cashregisters_.get(index);  } else {
        return cashregistersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public java.util.List<? extends com.example.grpc.server.grpcserver.cashregister.ProtoCashRegisterOrBuilder> 
         getCashregistersOrBuilderList() {
      if (cashregistersBuilder_ != null) {
        return cashregistersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cashregisters_);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.Builder addCashregistersBuilder() {
      return getCashregistersFieldBuilder().addBuilder(
          com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.Builder addCashregistersBuilder(
        int index) {
      return getCashregistersFieldBuilder().addBuilder(
          index, com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
     */
    public java.util.List<com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.Builder> 
         getCashregistersBuilderList() {
      return getCashregistersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister, com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.Builder, com.example.grpc.server.grpcserver.cashregister.ProtoCashRegisterOrBuilder> 
        getCashregistersFieldBuilder() {
      if (cashregistersBuilder_ == null) {
        cashregistersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister, com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister.Builder, com.example.grpc.server.grpcserver.cashregister.ProtoCashRegisterOrBuilder>(
                cashregisters_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        cashregisters_ = null;
      }
      return cashregistersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.server.grpcserver.cashregister.GetResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.server.grpcserver.cashregister.GetResponse)
  private static final com.example.grpc.server.grpcserver.cashregister.GetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.server.grpcserver.cashregister.GetResponse();
  }

  public static com.example.grpc.server.grpcserver.cashregister.GetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetResponse>() {
    public GetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetResponse> getParserForType() {
    return PARSER;
  }

  public com.example.grpc.server.grpcserver.cashregister.GetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

