// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CashRegister.proto

package com.example.grpc.server.grpcserver.cashregister;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.cashregister.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
   */
  java.util.List<com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister> 
      getCashregistersList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
   */
  com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister getCashregisters(int index);
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
   */
  int getCashregistersCount();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
   */
  java.util.List<? extends com.example.grpc.server.grpcserver.cashregister.ProtoCashRegisterOrBuilder> 
      getCashregistersOrBuilderList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashregisters = 1;</code>
   */
  com.example.grpc.server.grpcserver.cashregister.ProtoCashRegisterOrBuilder getCashregistersOrBuilder(
      int index);
}
