// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CashRegister.proto

package com.example.grpc.server.grpcserver.cashregister;

public interface ProtoCashRegisterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 added_amount = 2;</code>
   */
  int getAddedAmount();
}
