// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cashier.proto

package com.example.grpc.server.grpcserver.cashier;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.cashier.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.grpc.server.grpcserver.cashier.ProtoCashier cashier = 1;</code>
   */
  boolean hasCashier();
  /**
   * <code>.com.example.grpc.server.grpcserver.cashier.ProtoCashier cashier = 1;</code>
   */
  com.example.grpc.server.grpcserver.cashier.ProtoCashier getCashier();
  /**
   * <code>.com.example.grpc.server.grpcserver.cashier.ProtoCashier cashier = 1;</code>
   */
  com.example.grpc.server.grpcserver.cashier.ProtoCashierOrBuilder getCashierOrBuilder();
}
