// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CashRegister.proto

package com.example.grpc.server.grpcserver.cashregister;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.cashregister.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashRegister = 1;</code>
   */
  boolean hasCashRegister();
  /**
   * <code>.com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashRegister = 1;</code>
   */
  com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister getCashRegister();
  /**
   * <code>.com.example.grpc.server.grpcserver.cashregister.ProtoCashRegister cashRegister = 1;</code>
   */
  com.example.grpc.server.grpcserver.cashregister.ProtoCashRegisterOrBuilder getCashRegisterOrBuilder();
}
