// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CashRegister.proto

package com.example.grpc.server.grpcserver.cashregister;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.cashregister.DeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cash_register_id = 1;</code>
   */
  java.lang.String getCashRegisterId();
  /**
   * <code>string cash_register_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCashRegisterIdBytes();
}
