// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cashier.proto

package com.example.grpc.server.grpcserver.cashier;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.cashier.GetRequest)
    com.google.protobuf.MessageOrBuilder {
}
