// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dog.proto

package com.example.grpc.server.grpcserver.dog;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.dog.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.grpc.server.grpcserver.dog.ProtoDog dog = 1;</code>
   */
  boolean hasDog();
  /**
   * <code>.com.example.grpc.server.grpcserver.dog.ProtoDog dog = 1;</code>
   */
  com.example.grpc.server.grpcserver.dog.ProtoDog getDog();
  /**
   * <code>.com.example.grpc.server.grpcserver.dog.ProtoDog dog = 1;</code>
   */
  com.example.grpc.server.grpcserver.dog.ProtoDogOrBuilder getDogOrBuilder();
}
