// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dog.proto

package com.example.grpc.server.grpcserver.dog;

/**
 * Protobuf type {@code com.example.grpc.server.grpcserver.dog.GetResponse}
 */
public  final class GetResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.server.grpcserver.dog.GetResponse)
    GetResponseOrBuilder {
  // Use GetResponse.newBuilder() to construct.
  private GetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetResponse() {
    dogs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GetResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              dogs_ = new java.util.ArrayList<com.example.grpc.server.grpcserver.dog.ProtoDog>();
              mutable_bitField0_ |= 0x00000001;
            }
            dogs_.add(
                input.readMessage(com.example.grpc.server.grpcserver.dog.ProtoDog.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        dogs_ = java.util.Collections.unmodifiableList(dogs_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.server.grpcserver.dog.Dog.internal_static_com_example_grpc_server_grpcserver_dog_GetResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.server.grpcserver.dog.Dog.internal_static_com_example_grpc_server_grpcserver_dog_GetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.server.grpcserver.dog.GetResponse.class, com.example.grpc.server.grpcserver.dog.GetResponse.Builder.class);
  }

  public static final int DOGS_FIELD_NUMBER = 1;
  private java.util.List<com.example.grpc.server.grpcserver.dog.ProtoDog> dogs_;
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
   */
  public java.util.List<com.example.grpc.server.grpcserver.dog.ProtoDog> getDogsList() {
    return dogs_;
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
   */
  public java.util.List<? extends com.example.grpc.server.grpcserver.dog.ProtoDogOrBuilder> 
      getDogsOrBuilderList() {
    return dogs_;
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
   */
  public int getDogsCount() {
    return dogs_.size();
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
   */
  public com.example.grpc.server.grpcserver.dog.ProtoDog getDogs(int index) {
    return dogs_.get(index);
  }
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
   */
  public com.example.grpc.server.grpcserver.dog.ProtoDogOrBuilder getDogsOrBuilder(
      int index) {
    return dogs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < dogs_.size(); i++) {
      output.writeMessage(1, dogs_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < dogs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, dogs_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.server.grpcserver.dog.GetResponse)) {
      return super.equals(obj);
    }
    com.example.grpc.server.grpcserver.dog.GetResponse other = (com.example.grpc.server.grpcserver.dog.GetResponse) obj;

    boolean result = true;
    result = result && getDogsList()
        .equals(other.getDogsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDogsCount() > 0) {
      hash = (37 * hash) + DOGS_FIELD_NUMBER;
      hash = (53 * hash) + getDogsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.server.grpcserver.dog.GetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.dog.GetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.dog.GetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.dog.GetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.dog.GetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.server.grpcserver.dog.GetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.dog.GetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.dog.GetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.dog.GetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.dog.GetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.server.grpcserver.dog.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.server.grpcserver.dog.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.server.grpcserver.dog.GetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.server.grpcserver.dog.GetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.server.grpcserver.dog.GetResponse)
      com.example.grpc.server.grpcserver.dog.GetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.server.grpcserver.dog.Dog.internal_static_com_example_grpc_server_grpcserver_dog_GetResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.server.grpcserver.dog.Dog.internal_static_com_example_grpc_server_grpcserver_dog_GetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.server.grpcserver.dog.GetResponse.class, com.example.grpc.server.grpcserver.dog.GetResponse.Builder.class);
    }

    // Construct using com.example.grpc.server.grpcserver.dog.GetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDogsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (dogsBuilder_ == null) {
        dogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dogsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.server.grpcserver.dog.Dog.internal_static_com_example_grpc_server_grpcserver_dog_GetResponse_descriptor;
    }

    public com.example.grpc.server.grpcserver.dog.GetResponse getDefaultInstanceForType() {
      return com.example.grpc.server.grpcserver.dog.GetResponse.getDefaultInstance();
    }

    public com.example.grpc.server.grpcserver.dog.GetResponse build() {
      com.example.grpc.server.grpcserver.dog.GetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.example.grpc.server.grpcserver.dog.GetResponse buildPartial() {
      com.example.grpc.server.grpcserver.dog.GetResponse result = new com.example.grpc.server.grpcserver.dog.GetResponse(this);
      int from_bitField0_ = bitField0_;
      if (dogsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          dogs_ = java.util.Collections.unmodifiableList(dogs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dogs_ = dogs_;
      } else {
        result.dogs_ = dogsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.server.grpcserver.dog.GetResponse) {
        return mergeFrom((com.example.grpc.server.grpcserver.dog.GetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.server.grpcserver.dog.GetResponse other) {
      if (other == com.example.grpc.server.grpcserver.dog.GetResponse.getDefaultInstance()) return this;
      if (dogsBuilder_ == null) {
        if (!other.dogs_.isEmpty()) {
          if (dogs_.isEmpty()) {
            dogs_ = other.dogs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDogsIsMutable();
            dogs_.addAll(other.dogs_);
          }
          onChanged();
        }
      } else {
        if (!other.dogs_.isEmpty()) {
          if (dogsBuilder_.isEmpty()) {
            dogsBuilder_.dispose();
            dogsBuilder_ = null;
            dogs_ = other.dogs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dogsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDogsFieldBuilder() : null;
          } else {
            dogsBuilder_.addAllMessages(other.dogs_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.server.grpcserver.dog.GetResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.server.grpcserver.dog.GetResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.grpc.server.grpcserver.dog.ProtoDog> dogs_ =
      java.util.Collections.emptyList();
    private void ensureDogsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        dogs_ = new java.util.ArrayList<com.example.grpc.server.grpcserver.dog.ProtoDog>(dogs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.server.grpcserver.dog.ProtoDog, com.example.grpc.server.grpcserver.dog.ProtoDog.Builder, com.example.grpc.server.grpcserver.dog.ProtoDogOrBuilder> dogsBuilder_;

    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public java.util.List<com.example.grpc.server.grpcserver.dog.ProtoDog> getDogsList() {
      if (dogsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dogs_);
      } else {
        return dogsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public int getDogsCount() {
      if (dogsBuilder_ == null) {
        return dogs_.size();
      } else {
        return dogsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public com.example.grpc.server.grpcserver.dog.ProtoDog getDogs(int index) {
      if (dogsBuilder_ == null) {
        return dogs_.get(index);
      } else {
        return dogsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public Builder setDogs(
        int index, com.example.grpc.server.grpcserver.dog.ProtoDog value) {
      if (dogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDogsIsMutable();
        dogs_.set(index, value);
        onChanged();
      } else {
        dogsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public Builder setDogs(
        int index, com.example.grpc.server.grpcserver.dog.ProtoDog.Builder builderForValue) {
      if (dogsBuilder_ == null) {
        ensureDogsIsMutable();
        dogs_.set(index, builderForValue.build());
        onChanged();
      } else {
        dogsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public Builder addDogs(com.example.grpc.server.grpcserver.dog.ProtoDog value) {
      if (dogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDogsIsMutable();
        dogs_.add(value);
        onChanged();
      } else {
        dogsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public Builder addDogs(
        int index, com.example.grpc.server.grpcserver.dog.ProtoDog value) {
      if (dogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDogsIsMutable();
        dogs_.add(index, value);
        onChanged();
      } else {
        dogsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public Builder addDogs(
        com.example.grpc.server.grpcserver.dog.ProtoDog.Builder builderForValue) {
      if (dogsBuilder_ == null) {
        ensureDogsIsMutable();
        dogs_.add(builderForValue.build());
        onChanged();
      } else {
        dogsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public Builder addDogs(
        int index, com.example.grpc.server.grpcserver.dog.ProtoDog.Builder builderForValue) {
      if (dogsBuilder_ == null) {
        ensureDogsIsMutable();
        dogs_.add(index, builderForValue.build());
        onChanged();
      } else {
        dogsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public Builder addAllDogs(
        java.lang.Iterable<? extends com.example.grpc.server.grpcserver.dog.ProtoDog> values) {
      if (dogsBuilder_ == null) {
        ensureDogsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dogs_);
        onChanged();
      } else {
        dogsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public Builder clearDogs() {
      if (dogsBuilder_ == null) {
        dogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dogsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public Builder removeDogs(int index) {
      if (dogsBuilder_ == null) {
        ensureDogsIsMutable();
        dogs_.remove(index);
        onChanged();
      } else {
        dogsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public com.example.grpc.server.grpcserver.dog.ProtoDog.Builder getDogsBuilder(
        int index) {
      return getDogsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public com.example.grpc.server.grpcserver.dog.ProtoDogOrBuilder getDogsOrBuilder(
        int index) {
      if (dogsBuilder_ == null) {
        return dogs_.get(index);  } else {
        return dogsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public java.util.List<? extends com.example.grpc.server.grpcserver.dog.ProtoDogOrBuilder> 
         getDogsOrBuilderList() {
      if (dogsBuilder_ != null) {
        return dogsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dogs_);
      }
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public com.example.grpc.server.grpcserver.dog.ProtoDog.Builder addDogsBuilder() {
      return getDogsFieldBuilder().addBuilder(
          com.example.grpc.server.grpcserver.dog.ProtoDog.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public com.example.grpc.server.grpcserver.dog.ProtoDog.Builder addDogsBuilder(
        int index) {
      return getDogsFieldBuilder().addBuilder(
          index, com.example.grpc.server.grpcserver.dog.ProtoDog.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
     */
    public java.util.List<com.example.grpc.server.grpcserver.dog.ProtoDog.Builder> 
         getDogsBuilderList() {
      return getDogsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.server.grpcserver.dog.ProtoDog, com.example.grpc.server.grpcserver.dog.ProtoDog.Builder, com.example.grpc.server.grpcserver.dog.ProtoDogOrBuilder> 
        getDogsFieldBuilder() {
      if (dogsBuilder_ == null) {
        dogsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.grpc.server.grpcserver.dog.ProtoDog, com.example.grpc.server.grpcserver.dog.ProtoDog.Builder, com.example.grpc.server.grpcserver.dog.ProtoDogOrBuilder>(
                dogs_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        dogs_ = null;
      }
      return dogsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.server.grpcserver.dog.GetResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.server.grpcserver.dog.GetResponse)
  private static final com.example.grpc.server.grpcserver.dog.GetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.server.grpcserver.dog.GetResponse();
  }

  public static com.example.grpc.server.grpcserver.dog.GetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetResponse>() {
    public GetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetResponse> getParserForType() {
    return PARSER;
  }

  public com.example.grpc.server.grpcserver.dog.GetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

