// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dog.proto

package com.example.grpc.server.grpcserver.dog;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.dog.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
   */
  java.util.List<com.example.grpc.server.grpcserver.dog.ProtoDog> 
      getDogsList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
   */
  com.example.grpc.server.grpcserver.dog.ProtoDog getDogs(int index);
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
   */
  int getDogsCount();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
   */
  java.util.List<? extends com.example.grpc.server.grpcserver.dog.ProtoDogOrBuilder> 
      getDogsOrBuilderList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.dog.ProtoDog dogs = 1;</code>
   */
  com.example.grpc.server.grpcserver.dog.ProtoDogOrBuilder getDogsOrBuilder(
      int index);
}
