// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdatingBalance.proto

package com.example.grpc.server.grpcserver.updating;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.updating.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cash_registerId = 1;</code>
   */
  java.lang.String getCashRegisterId();
  /**
   * <code>string cash_registerId = 1;</code>
   */
  com.google.protobuf.ByteString
      getCashRegisterIdBytes();

  /**
   * <code>int32 added_amount = 2;</code>
   */
  int getAddedAmount();
}
