// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dog.proto

package com.example.grpc.server.grpcserver.dog;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.dog.DeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dog_id = 1;</code>
   */
  java.lang.String getDogId();
  /**
   * <code>string dog_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getDogIdBytes();

  /**
   * <code>string cash_register_id = 2;</code>
   */
  java.lang.String getCashRegisterId();
  /**
   * <code>string cash_register_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getCashRegisterIdBytes();
}
