// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Accessory.proto

package com.example.grpc.server.grpcserver.accessory;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.accessory.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.grpc.server.grpcserver.accessory.ProtoAccessory accessory = 1;</code>
   */
  boolean hasAccessory();
  /**
   * <code>.com.example.grpc.server.grpcserver.accessory.ProtoAccessory accessory = 1;</code>
   */
  com.example.grpc.server.grpcserver.accessory.ProtoAccessory getAccessory();
  /**
   * <code>.com.example.grpc.server.grpcserver.accessory.ProtoAccessory accessory = 1;</code>
   */
  com.example.grpc.server.grpcserver.accessory.ProtoAccessoryOrBuilder getAccessoryOrBuilder();
}
