// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Accessory.proto

package com.example.grpc.server.grpcserver.accessory;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.accessory.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.grpc.server.grpcserver.accessory.ProtoAccessory accessories = 1;</code>
   */
  java.util.List<com.example.grpc.server.grpcserver.accessory.ProtoAccessory> 
      getAccessoriesList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.accessory.ProtoAccessory accessories = 1;</code>
   */
  com.example.grpc.server.grpcserver.accessory.ProtoAccessory getAccessories(int index);
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.accessory.ProtoAccessory accessories = 1;</code>
   */
  int getAccessoriesCount();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.accessory.ProtoAccessory accessories = 1;</code>
   */
  java.util.List<? extends com.example.grpc.server.grpcserver.accessory.ProtoAccessoryOrBuilder> 
      getAccessoriesOrBuilderList();
  /**
   * <code>repeated .com.example.grpc.server.grpcserver.accessory.ProtoAccessory accessories = 1;</code>
   */
  com.example.grpc.server.grpcserver.accessory.ProtoAccessoryOrBuilder getAccessoriesOrBuilder(
      int index);
}
