// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Accessory.proto

package com.example.grpc.server.grpcserver.accessory;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.accessory.GetRequest)
    com.google.protobuf.MessageOrBuilder {
}
