// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Accessory.proto

package com.example.grpc.server.grpcserver.accessory;

public interface ProtoAccessoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.accessory.ProtoAccessory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string color = 2;</code>
   */
  java.lang.String getColor();
  /**
   * <code>string color = 2;</code>
   */
  com.google.protobuf.ByteString
      getColorBytes();

  /**
   * <code>int32 price = 3;</code>
   */
  int getPrice();
}
